global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysqld-exporter:9104']
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ["node-exporter:9100"]
