apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: http://mysql:3306
    user: root
    jsonData:
      database: isuconp
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: root

  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
      uid: PBFA97CFB590B2093

  - name: Grafana Pyroscope
    type: grafana-pyroscope-datasource
    uid: Pyroscope
    url: http://pyroscope:4040
    editable: true
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000